name: JoRoberts
favicon: null
layout_spectrum: 0.31407746602781117
typography_spectrum: 0.8836723444983363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6022765436209738
  lightness: 0.070317946607247
  saturation: 0.9000776810571551
  rhythmicContrast: 0.2848739083856344
purpose: []
