name: JoRoberts
favicon: null
layout_spectrum: 0.9056
typography_spectrum: 0.21508
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0605'
    - '#ffffff'
    - '#75726b'
    - '#ae2f70'
    - '#ff70c0'
  brandStrength: 0.625
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
